# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_key', models.IntegerField(help_text='Id of the product, unique identifier of the product at its origin.', verbose_name='Product Key')),
                ('prd_name', models.CharField(max_length=30, verbose_name='Name')),
                ('prd_description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
    ]
